services:
  deskmotion:
    image: ${DOCKER_REGISTRY-}deskmotion
    build:
      context: .
      dockerfile: DeskMotion/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};Include Error Detail=true
      - DeskApi__BaseUri=http://host.docker.internal:8000/api/${SIM_VERSION}/${SIM_API}/
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/LocalhostDevCert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=postgres
    ports:
      - ${ASPNETCORE_HTTP_PORTS}:8080
      - ${ASPNETCORE_HTTPS_PORTS}:8081
    volumes:
      - ./certs:/app/certs:ro

  deskmotion.db:
    image: postgres:latest
    container_name: deskmotion.db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - deskmotion_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - ${PGA_PORT}:80
    depends_on:
      - deskmotion.db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  deskmotion.sim:
    image: respectmathias/wifi2ble-box-simulator:latest
    ports:
      - ${SIM_PORT}:8000

volumes:
  deskmotion_data:
  pgadmin_data:
