blank_issues_enabled: false
contact_links:
  - name: "Bug Report"
    url: "/issues/new?template=bug_report.md"
    about: "Report a bug."
  - name: "Feature Request"
    url: "/issues/new?template=feature_request.md"
    about: "Request a new feature."
