name: Add Issues to Project Board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add Issue to Project
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/SP-SDU/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, needs-triage
          label-operator: NOT
